CREATE TABLE ORDER_ITEM(
    ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    ORDER_ID BIGINT,
    PRODUCT VARCHAR(50),
    AMOUNT INT,
    FOREIGN KEY (ORDER_ID) REFERENCES ORDER_ENTITY(ORDER_ID)
);